#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(dead_code)]
pub enum CommandId {
    // File
    NewDocument,
    Open,
    Save,
    SaveAs,
    ExportPng,
    ExportJpeg,
    ExportOra,
    ImportImageAsLayer,
    ImportReferenceImage,
    ImportBrushPreset,
    DocumentInfo,
    Preferences,
    Exit,

    // Edit
    Undo,
    Redo,
    Cut,
    Copy,
    CopyMerged,
    Paste,
    PasteAsNewLayer,
    Clear,
    Fill,

    // Canvas
    ResizeCanvas,
    ResizeImage,
    CropToSelection,
    TrimTransparent,
    RotateCanvasViewLeft,
    RotateCanvasViewRight,
    ResetRotation,
    FlipViewHorizontal,
    FlipCanvasHorizontal,
    FlipCanvasVertical,
    FitToScreen,
    ActualSize,
    ResetView,

    // Layer
    NewRasterLayer,
    NewFolder,
    NewVectorLayer,
    DuplicateLayer,
    DeleteLayer,
    RenameLayer,
    MergeDown,
    MergeVisible,
    FlattenImage,
    ClearLayer,
    FillLayer,
    LayerProperties,
    AddLayerMask,
    ApplyLayerMask,
    DeleteLayerMask,
    ToggleLayerMask,
    InvertLayerMask,
    ToggleLockAlpha,
    ToggleClipping,
    ConvertToRaster,
    TransformLayer,

    // Selection
    SelectAll,
    Deselect,
    Reselect,
    InvertSelection,
    SelectionGrow,
    SelectionShrink,
    SelectionFeather,
    SelectionSmooth,
    SelectionBorder,
    TransformSelection,
    ToggleSelectionOverlay,

    // View
    ShowNavigator,
    ShowColorPanel,
    ShowLayers,
    ShowBrushPresets,
    ShowToolOptions,
    ShowReferenceImages,
    ShowStatusBar,
    ShowGrid,
    ShowSymmetry,
    Fullscreen,
    MinimalUi,
    ResetWorkspace,
    ToggleMirrorView,

    // Window
    WorkspaceDefault,
    WorkspaceCompact,
    WorkspacePainting,
    WorkspaceInking,
    UiScale80,
    UiScale100,
    UiScale125,
    UiScale150,
    ThemeLight,
    ThemeGray,
    ThemeDark,

    // Help
    QuickStart,
    KeyboardShortcuts,
    TabletDiagnostics,
    PerformanceHud,
    About,
    OpenConfigFolder,

    // Tools
    ToolBrush,
    ToolEraser,
    ToolFill,
    ToolGradient,
    ToolRectSelect,
    ToolEllipseSelect,
    ToolLasso,
    ToolPolygonLasso,
    ToolMagicWand,
    ToolMove,
    ToolTransform,
    ToolColorPicker,
    ToolHand,
    ToolZoom,
    ToolRotateView,
    ToolLine,
    ToolShape,
}
